In [1]:
import numpy as np
import time


In [2]:
np.array([1, 2, 3])

array([1, 2, 3])

In [3]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

In [4]:
A.shape

(2, 3)

In [5]:
print(A)
print(B)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]


In [6]:
C = np.dot(A, B)

In [8]:
C = A @ B

In [10]:
print(C)

[[ 58  64]
 [139 154]]


In [11]:
square_matrix = np.array([[4, 2],
                          [1, 3]])

print("\nSquare Matrix:")
print(square_matrix)

# Determinant
det = np.linalg.det(square_matrix)
print("\nDeterminant of Matrix:")
print(det)

# Inverse
inverse = np.linalg.inv(square_matrix)
print("\nInverse Matrix:")
print(inverse)

# Eigenvalues and Eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(square_matrix)

print("\nEigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

tensor = np.arange(24).reshape(2, 3, 4)

print("\n3D Array (Tensor):")
print(tensor)

print("\nShape of Tensor:")
print(tensor.shape)

print("\nNumber of Dimensions:")
print(tensor.ndim)

print("\nElement at Position [1,2,3]:")
print(tensor[1, 2, 3])

size = 1000000

x = np.arange(size)
y = np.arange(size)

# Vectorized Addition
start = time.time()

result_vectorized = x + y

vectorized_time = time.time() - start

print("\nVectorized Addition Time:")
print(vectorized_time, "seconds")


# Loop-Based Addition
start = time.time()

result_loop = np.zeros(size)

for i in range(size):
    result_loop[i] = x[i] + y[i]

loop_time = time.time() - start

print("\nLoop-Based Addition Time:")
print(loop_time, "seconds")


# Speed Comparison
speedup = loop_time / vectorized_time

print("\nSpeedup Factor:")
print(speedup)

print("\nMean of Tensor:")
print(np.mean(tensor))

print("\nMaximum Value in Tensor:")
print(np.max(tensor))

print("\nSum of All Elements in Tensor:")
print(np.sum(tensor))


Square Matrix:
[[4 2]
 [1 3]]

Determinant of Matrix:
10.000000000000002

Inverse Matrix:
[[ 0.3 -0.2]
 [-0.1  0.4]]

Eigenvalues:
[5. 2.]

Eigenvectors:
[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]

3D Array (Tensor):
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

Shape of Tensor:
(2, 3, 4)

Number of Dimensions:
3

Element at Position [1,2,3]:
23

Vectorized Addition Time:
0.0039119720458984375 seconds

Loop-Based Addition Time:
1.388258934020996 seconds

Speedup Factor:
354.87445148707945

Mean of Tensor:
11.5

Maximum Value in Tensor:
23

Sum of All Elements in Tensor:
276


In [12]:
import numpy as np


A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)


C = np.dot(A, B)

print("\nMatrix Multiplication (A × B):")
print(C)

Matrix A:
[[1 2 3]
 [4 5 6]]

Matrix B:
[[ 7  8]
 [ 9 10]
 [11 12]]

Matrix Multiplication (A × B):
[[ 58  64]
 [139 154]]
